### ISSUE TITLE
Tests should not depend on a roscore

### ISSUE THREAD

**Issue by lucbettaieb** [cwru-robotics/cwru_vision#10]
```
[==========] Running 1 test from 1 test case.

[----------] Global test environment set-up.

[----------] 1 test from ManualLabelingTest

[ RUN      ] ManualLabelingTest.testManualLabelingCallback

[ERROR] [1469548564.653099380]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...

... logging to /home/travis/.ros/log/rostest-testing-gce-9d0336fe-68b2-4b5f-a3e5-42f88bc16a60-7690.log
```

That's why the build failed.  Testing shouldn't need a roscore running to work.

Or, I guess if you're using rostest, you may need to configure travis to work w that.

**Comment by biocubed** [comment]
Tipakorn, please fixes the tests you wrote

**Comment by lucbettaieb** [comment]
@tipakorng You may need to edit the .travis.yml file in order to make it work happily with rostest - or just have it skip over them altogether; since I don't know if it's reasonable for a roscore to run on the VM building the software and running the tests.

**Comment by tipakorng** [comment]
rostest is doing nothing at the moment, and with the new pull request, gtest is also doing nothing. I left them in the test folder as place holders. Would you like me to remove them?

**Comment by lucbettaieb** [comment]
I think you may need to just un-do the rostest ones.  When you are running the tests on your machine, do you have a roscore running?  Also, with what you are testing, is it depending on getting information from topics or anything ros-related?  Are there nodehandles?  This will cause things to need to roscore to run.

You don't need to get rid of the tests, but it may be better to not have them need a roscore running.

You can always try editing the .travis.yml file to make things happy and run a roscore when running your tests on the VM; but I'm not sure how that will go down.

**Comment by tipakorng** [comment]
rostest requires roscore, but since I'm not doing anything with it right now, I'll remove rostest and leave only gtest. How does that sound?

**Comment by lucbettaieb** [comment]
That should work just fine!

For future reference, it may be best to avoid using rostest altogether and always try to make libraries not depend on ROS-specific code.  Then, to tie the library into ROS, have a class with {library_name}_node.cpp that does all the subscribing, publishing, and what have you.
