### ISSUE TITLE
[rainyday] A lot of the old code should be linted

### ISSUE THREAD

**Issue by lucbettaieb** [cwru-robotics/cwru_vision#16]
just noticed when I was perusing through the library

**Comment by biocubed** [comment]
Its time to clean out the lint traps!!!!, seriously though if it is cool, can @lucbettaieb , @tipakorng help do a file or 2 each?

**Comment by tipakorng** [comment]
How do I start?

**Comment by lucbettaieb** [comment]
listed as rainyday for a reason.  this is not urgent and should not be done unless there is a lull
